rails d model Player
rails d model Charactor
rails d model Race
rails d model RaceAbility
rails d model Klass
rails d model KlssAbility
rails d model MainKlass
rails d model SupportKlass
rails d model LevelUp
rails d model BaseAbilityUp
rails d model SkillUp
rails d model Ability
rails d model Skill
rails d model SkillBonus
rails d model Bonus
rails d model Item
rails d model ItemRequireKlass
rails d model ItemBonus
rails d model CharactorItem
rails d model Effect
rails d model Timing
rails d model RollType
rails d model Target
rails d model Apart
rails d model Critical
rails d model Limitation
