rails g rspec:model Player
rails g rspec:model Charactor
rails g rspec:model Race
rails g rspec:model RaceAbility
rails g rspec:model Klass
rails g rspec:model KlassAbility
rails g rspec:model MainKlass
rails g rspec:model SupportKlass
rails g rspec:model LevelUp
rails g rspec:model BaseAbilityUp
rails g rspec:model SkillUp
rails g rspec:model Ability
rails g rspec:model Skill
rails g rspec:model SkillBonus
rails g rspec:model Bonus
rails g rspec:model Item
rails g rspec:model ItemRequireKlass
rails g rspec:model ItemBonus
rails g rspec:model CharactorItem
rails g rspec:model Effect
rails g rspec:model Timing
rails g rspec:model RollType
rails g rspec:model Target
rails g rspec:model Distance
rails g rspec:model Critical
rails g rspec:model Limitation
