# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 496ff38c2d5177c8115b6c632db0ffd689f70492b1ac197effc87618aeae0130404afe18b3b03326b8e35e20b7347e21a84838d1ce1a92fef88dcbad06c33092

test:
  secret_key_base: d274d525e4ad249a4ab073d3e758087c7cf5eff75e199fd9e36745bfe3ef718273dc2110c3ee2d4c268c63b6a0dcee997859a6af35956140e272fa48ae3242b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
